FROM public.ecr.aws/lambda/nodejs:24

# Swap RIC
ADD build-artifacts/aws-lambda-ric-*.tgz /tmp/
RUN mv /tmp/package/* /var/runtime/ && rm -rf /tmp/package

# Inject task
ENV LAMBDA_TASK_ROOT="/var/task"
COPY resources/index.cjs /var/task/
ENV _HANDLER="index.handler"

ENTRYPOINT ["/usr/local/bin/aws-lambda-rie"]
CMD ["/var/runtime/bootstrap"]
