name: CI

on:
  push:
    branches: [nodejs24.x]
  pull_request:
    branches: [nodejs24.x]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Build and test
        run: npm run build


